name: Code Quality
on: 
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint /apis
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./apis"
          version: "~= 24.0"
      - name: Lint /tests
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests"
          version: "~= 24.0"
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Mypy
        run: pip install mypy types-python-dateutil types-requests
      - name: Type Check /apis/basic-api
        run: mypy ./apis/basic-api --strict --ignore-missing-imports
      - name: Type Check /apis/production-grade-api
        run: mypy ./apis/production-grade-api --strict --ignore-missing-imports